### ISSUE TITLE
Can't get vsc-ember-cli to work in vscode 0.10.11

### ISSUE THREAD

**Issue by nicbourgoin** [felixrieseberg/vsc-ember-cli#13]
I am unable to get it to work altogether:

I installed it using the command palette and entering "ext install vsc-ember-cli".

Once installed, I do have the options in the palette. Picking any option (Ember:Generate blueprint, component, test-component) doesn't produce any result however. The output windows does not have "Ember" in the dropdown list even after I added VSC_EMBER_CLI_DEBUG setting to 1 in both my account and global system environment variable.

Please note that VSC is new to me and so is ember-cli. I've used ember with ember data inside visual studio but since ember is moving toward ember-cli we are going to start using vsc for front end dev.

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! There addon isn't perfect and there are a few tiny things that can make it trip up - is the ember-cli app the root folder inside VSCode?

**Comment by nicbourgoin** [comment]
Yes, ember-cli app is the root folder as shown here:

![image](https://cloud.githubusercontent.com/assets/287070/14096533/920f1030-f537-11e5-95eb-3ecdc8256e52.png)

Could I have done something wrong with the environment variable? The output isn't giving me anything at all to report.
