### ISSUE TITLE
Enable ES6 by default

### ISSUE THREAD

**Issue by dschmidt** [felixrieseberg/vsc-ember-cli#2]
Hey,

would it be possible for this plugin to enable ES6 support automatically?
First had to lookup how to use the `jsonconfig.json`, while you certainly want to use modules if you use ember-cli and this plugin :-)

BR
Domme

**Comment by felixrieseberg** [comment]
Hey @dschmidt, you're totally right. In fact, we'll probably just do that for VS Code proper.

See: https://github.com/Microsoft/vscode/pull/337

**Comment by dschmidt** [comment]
Fair enough, even better I guess :)

**Comment by dschmidt** [comment]
Mh, as it was rejected in the main project ... is there still a way to do it here?

**Comment by felixrieseberg** [comment]
I'm not super happy about the solution, but yes, we can automatically create the necessary files. I'll enable that today.

**Comment by dschmidt** [comment]
Great!

**Comment by felixrieseberg** [comment]
Done! c26b23ea3eb0487ce66b0f81d0b99011294d9112

**Comment by dschmidt** [comment]
That was quick. Cheers! :beers:

Btw I dropped you a few lines on Slack, appreciated if you mind looking at them too ;-)
