### ISSUE TITLE
No way to use Pod structure in component generators

### ISSUE THREAD

**Issue by Koi-bk** [felixrieseberg/vsc-ember-cli#39]
There's no (apparent) way to use the --pod flag inside a generate blueprint command, is this intended and you expect people using pods to have the pod flag permanently set to "true" in the .ember-cli file?

**Comment by t-sauer** [comment]
We have an settings file where we could put in an extra setting to specify if pods are used or not. On the other hands pods are dying and I don't know if it makes sense to support it.

**Comment by Koi-bk** [comment]
Ah, yeah just followed the rabbit down the module unification RFC hole. I'd say just leave it out then based on that discussion. Thanks for the speedy reply!

**Comment by knownasilya** [comment]
Still a good thing to have, especially for existing projects.
