### ISSUE TITLE
HTML one-way controls for form

### ISSUE THREAD

**Issue by karellm** [felixrieseberg/vsc-ember-cli#51]
I just wanted to suggest the following Handlebars snippets to create one-way form controls:

```json
{
	"One-Way HTML input": {
		"prefix": "input",
		"body": [
			"<input",
			"\t type=\"${1:text}\"",
			"\t value={{${2:value}}}",
			"\t oninput={{action (mut ${2:value}) value=\"target.value\"}}",
			">"
		],
		"description": "HTML input with one-way binding"
	},
	"One-Way HTML textarea": {
		"prefix": "textarea",
		"body": [
			"<textarea",
			"\t value={{${1:value}}}",
			"\t oninput={{action (mut ${1:value}) value=\"target.value\"}}",
			">",
			"</textarea>",
		],
		"description": "HTML textarea with one-way binding"
	},
	"One-Way HTML input radio": {
		"prefix": "radio",
		"body": [
			"<input",
			"\t type=\"radio\"",
			"\t checked={{eq ${1:value} ${2:option}}}",
			"\t onclick={{action (mut ${1:value}) ${2:option}}}",
			">"
		],
		"description": "HTML input radio with one-way binding"
	},
	"One-Way HTML input checkbox": {
		"prefix": "checkbox",
		"body": [
			"<input",
			"\t type=\"checkbox\"",
			"\t checked={{${1:value}}}",
			"\t onclick={{action (mut ${1:value}) value=\"target.checked\"}}",
			">"
		],
		"description": "HTML input checkbox with one-way binding"
	}
}
```

**Comment by locks** [comment]
Speaking from a Learning team perspective, we do not want people to use `mut` over `{{input}}`.
This is effectively a two-way bound input with worse ergonomics.

**Comment by karellm** [comment]
@locks I'm getting back to Ember after a little absence. I got these from [ember-one-way-controls](https://github.com/DockYard/ember-one-way-controls). Can you explain what you mean by "a learning team perspective"? Do you mean that `mut` is too much overhead for less technical people or that you found issue in using `mut`? 

It is indeed a "two-way binding" but that is declarative. If you need it one-way (very rarely useful for form inputs I agree), it is possible. That said, I believe there is benefit in exposing the "data down, action up" in how we write the code. Consistency is more important the syntax sugar in my experience. I prefer a team sticking to a single style.

**Comment by locks** [comment]
> Can you explain what you mean by "a learning team perspective"? 

The leadership of Ember is organized into [different teams](https://emberjs.com/team/), one of them is the Learning team.

> Do you mean that `mut` is too much overhead for less technical people or that you found issue in using `mut`?

`mut` is not something that we generally want people to use. One reason is that templates are currently two-way bound so everything is "mut" by default. Another is the reduced ergonomics, by which I mean that you have to "know" more stuff to be able to use the HTML input, thusly easier to get wrong.

Since it public API, it is perfectly fine to use it in your projects, and you'll have the semver guarantees that Ember provides, but if you consult the Guides the position is "use `{{input}}`, they're fine" ;P

Ping me for more details regarding `mut`.

**Comment by karellm** [comment]
Thanks for the clarification, makes total sense. I will close this then

**Comment by locks** [comment]
Thank you for reaching out! If you make your own plugin for these completions, let people know on Slack, `#topic-editors` channel.
