### ISSUE TITLE
Allow for use of ember-cli installed only in Project's `node_modules`, not globally

### ISSUE THREAD

**Issue by orospakr** [felixrieseberg/vsc-ember-cli#7]
In order to version freeze ember-cli along with the rest of my project, I always include it in package.json and then invoke it like:

```
./node_modules/.bin/ember server
```

It would be awesome if vsc-ember-cli were to allow for either manually overriding (relative to the directory of the project) the path to `ember` or even something more automatic than that.

Thank you!

**Comment by Turbo87** [comment]
@orospakr you don't have to do that because the `ember` command is automatically delegating back to the project-specific version

**Comment by felixrieseberg** [comment]
@Turbo87 is totally correct, so I'm closing this for now - conveniently, ember is smart enough to do that without us telling it to :+1:

**Comment by orospakr** [comment]
Yeah, but it still requires having ember-cli installed globally, which I actually try to avoid, because it's still a an external dependency.  But, perhaps I'm too much of a purist ;)

**Comment by Turbo87** [comment]
fair point. actually a coworker of mine recently had issues with the global ember not being found by this plugin, which would probably be resolved if the local ember was used directly.

**Comment by felixrieseberg** [comment]
Yeah, if anyone wants to make a quick PR, I'd gladly merge. One mean requirement though: It should still call the global ember as a fallback, otherwise stuff like `ember new` or `ember init` won't work.
